### ISSUE TITLE
AUCell error

### ISSUE THREAD

**Issue by joyduck** [chuiqin/irGSEA#6]
Pretty sure this error has come up recently due to an update of some R packages, not sure if it's from AUCell through.
run this:

pbmc3k.final <- irGSEA.score(object = pbmc3k.final, assay = "RNA", 
                             slot = "data", seeds = 123, ncores = 1,
                             min.cells = 3, min.feature = 0,
                             custom = F, geneset = NULL, msigdb = T, 
                             species = "Homo sapiens", category = "H",  
                             subcategory = NULL, geneid = "symbol",
                             method = c("AUCell", "UCell", "singscore", 
                                        "ssgsea"),
                             aucell.MaxRank = NULL, ucell.MaxRank = NULL, 
                             kcdf = 'Gaussian')

get the error below:

Calculate AUCell scores
Error in .AUCell_buildRankings(exprMat = exprMat, featureType = featureType,  : 
  To use a dgCMatrix as input set 'splitByBlocks=TRUE'.

**Comment by chuiqin** [comment]
这个错误的原因是因为AUCell包更新了，在运行AUCell_buildRankings函数时，需要将参数splitByBlocks设置为T。我更新了irGSEA包，解决了这个问题，你可以重新安装irGSEA包解决这个问题（devtools::install_github("chuiqin/irGSEA")）。但如果你不想更新irGSEA包的话，可以将AUCell包的版本降到1.14.0，也可以解决这个问题。

**Comment by chuiqin** [comment]
The reason for this error is because the AUCell package has been updated. When running the AUCell_buildRankings function, the parameter splitByBlocks needs to be set to T. I updated the irGSEA package, which solved the problem, you can reinstall the irGSEA package to solve the problem (devtools::install_github("chuiqin/irGSEA")). But if you don't want to update the irGSEA package, you can downgrade the version of the AUCell package to 1.14.0, which can also solve this problem.

**Comment by liang58** [comment]
> The reason for this error is because the AUCell package has been updated. When running the AUCell_buildRankings function, the parameter splitByBlocks needs to be set to T. I updated the irGSEA package, which solved the problem, you can reinstall the irGSEA package to solve the problem (devtools::install_github("chuiqin/irGSEA")). But if you don't want to update the irGSEA package, you can downgrade the version of the AUCell package to 1.14.0, which can also solve this problem.

i'm not sure why this error showing below happens when calculates AUCell score? @chuiqin 

Validating object structure
Updating object slots
Ensuring keys are in the proper strucutre
Ensuring feature names don't have underscores or pipes
Object representation is consistent with the most current Seurat version
Calculate AUCell scores

Error in .local(exprMat, plotStats, nCores, mctype, keepZeroesAsNA, verbose,  : 
  unused argument (splitByBlocks = TRUE)

**Comment by joyduck** [comment]
you probably want to update your AUCell package or go back to use the old version of irGSEA.
